@url = https://localhost:44377/customers
@customerId = 1daa740a-80a6-4b63-b4a3-f3daef7629f8

###
POST {{url}}
Content-Type: application/json

{
  "email": "user1@melonpay.io"
}

###
GET {{url}}/{{customerId}}